remote_theme: jekyll/minima

title: shh.sh
author: worldwise001
description: >
  My personal site for documenting my building stuff and tinkering with electronics and computers.

#show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: worldwise001
    github:  worldwise001
    linkedin: shharvey
    youtube: worldwise001
    instagram: sprinks_n_izzy
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - guides.md
 - projects.md
 - snippets.md
 - about.md
 - pubs.md

paginate: 5

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap
