remote_theme: jekyll/minima

title: shh.sh
author: worldwise001
#email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Public notes and things from worldwise001.
# social links
twitter_username: worldwise001
github_username:  worldwise001
linkedin_username: shharvey
youtube_username: worldwise001
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - projects.md
 - snippets.md
 - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
